name: mobileportfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  collection: ^1.17.2
  http: ^0.13.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
